# Wire up travis
language: python
sudo: false

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.5
          env: TOXENV=py35
        - python: 2.7
          env: TOXENV=py27-pyramid15
        - python: 2.7
          env: TOXENV=py27-pyramid16
        - python: 2.7
          env: TOXENV=py27-pyramid17


install:
  - travis_retry pip install tox

script:
  - travis_retry tox
